# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1df9003fcd38bcc3f6e3a7d1dd90ce3fcfc4dc9aa0fbe8d03031b859770a383b337430c77a9106bfd96a3adf96cedc3c4da9db3612250514fcac0fa147054b7

test:
  secret_key_base: 8742d48a3b2b40167adeb24814380b6f059df24895d2c89d009535c522cff512aa105fc0f284b88fc674ddd5bd20391168118c21dcec9535b7ffca663d61d1b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
